Encapsulate http client with Axios
Innovate-Future-Foundation/Frontend pull request #5
Opened 2024-12-11 05:18 UTC by qingyanyang

This PR sets up Axios client encapsulation and builds an example API encapsulation layer to provide a structured approach for managing API requests and services. It also establishes a service folder structure for better organization and maintainability.

Key Features

	1.	Axios Client Encapsulation:
	•	Configured a reusable Axios instance with interceptors for handling common scenarios such as timeouts, network errors, and HTTP errors.
	•	Default configuration includes base URL, timeout settings, and headers.

	2.	Example API Encapsulation:
	•	Demonstrated encapsulating API requests in a dedicated module using the Axios client.

	3.	Service Folder Structure:
	•	Organized API services into a services directory to promote a clean and scalable architecture.
	•	Included subfolders and files for separating concerns (e.g., apiClient.ts, tourService.ts).

	4.	Testing Integration:
	•	Integrated Vitest for unit testing the Axios client and API encapsulation.

Testing Method

	1.	Unit Testing:
	•	Used Vitest to test the  API encapsulation with mocked axios.
	•	Simulated various error scenarios to validate interceptor behavior.

        2.	Commands:
	•	Run tests with npm run test.
	
Screenshot

<img width="266" alt="Screenshot 2024-12-11 at 3 47 27 pm" src="https://github.com/user-attachments/assets/a62e90fe-dde8-4f32-a73f-adab98cacb26">

<img width="530" alt="Screenshot 2024-12-11 at 3 30 21 pm" src="https://github.com/user-attachments/assets/401ca477-4f11-4c63-92b3-704b02e2972a">

Related Ticket

JIRA Ticket: IF-21 (JIRA is temporarily not accessible)

2024-12-13 14:14 UTC, LH-Song requested changes

2024-12-13 14:14 UTC, LH-Song commented on src/services/httpClient.ts
> +  res => {
Did you guys have settings similar to .eslintrc.json? When using TypeScript, strict typing and data validation should be enabled. I noticed several places where strict request parameter types and return data types are needed.
```suggestion
  (res: AxiosResponse) => {
```

2024-12-15 04:59 UTC, qingyanyang commented on src/services/httpClient.ts
> +appRequest.interceptors.response.use(
may refactor this in the future

2024-12-15 04:59 UTC, qingyanyang commented on src/services/httpClient.ts
> +  timeout: 30 * 1000,
I made all constants in one place

2024-12-15 05:01 UTC, LH-Song approved these changes
LGTM 🚀🚀

2024-12-15 05:02 UTC, merged